# -*- coding: utf-8 -*-
"""AI Search Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EA6nIzrH2nSNJB6y-hhyJogdPaIV-qg9
"""



"""# BORRADOR LOL"""

a_list = ['a','c','b','a']
a_str = ''
for i in a_list:
  a_str += i

a_list

a_str

def new_list(a_list):
  a_str = ''
  for i in a_list:
      a_str += i
  print(a_str)
  return a_str

a_list

a_str = 'cbc'
a_list = [i for i in a_str]

n = len(a_list)
print(a_str)
k = 0

while len(a_str) != 1:
    
  for i in range(n):
    
    if n - i >= 3:
      if a_str[i:i+3] == 'bbc':               # 4
        a_list[i:i+3] = ['b','c','0']
        a_list.remove('0'); print(4)
        a_str = new_list(a_list); break
      elif a_str[i:i+3] == 'abb':             # 3
        a_list[i:i+3] = ['0','a','b']
        a_list.remove('0'); print(3)
        a_str = new_list(a_list); break
  
  for i in range(n):
    if a_str[i:i+2] == 'SS':                  # 2
      a_list[i:i+2] = ['S', '0']
      a_list.remove('0'); print(2)
      a_str = new_list(a_list); break
    elif a_str[i:i+2] == 'bc':                # 8
      a_list[i:i+2] = ['a', 'b']; print(8)
      a_str = new_list(a_list); break


  for i in range(n):
    if a_str[i:i+2] == 'ba':                # 5
      a_list[i:i+2] = ['b', 'c']; print(5)
      a_str = new_list(a_list); break
    elif a_str[i:i+2] == 'aa':                
      a_list[i:i+2] = ['a', 'c']; print(5)
      a_str = new_list(a_list); break
    
    elif a_str[i:i+2] == 'ca':                # 6
      a_list[i:i+2] = ['b', 'a']; print(6)
      a_str = new_list(a_list); break
    elif a_str[i:i+2] == 'ac':              
      a_list[i:i+2] = ['a', 'b']; print(6)
      a_str = new_list(a_list); break
    elif a_str[i:i+2] == 'cc':              
      a_list[i:i+2] = ['b', 'c']; print(6)
      a_str = new_list(a_list); break
  
  for i in range(n):
    if a_str[i:i+2] == 'ab':                # 7
      a_list[i:i+2] = ['b', 'c']; print(7)
      a_str = new_list(a_list); break
  
  for i in range(n):  
    if a_str[i:i+2] == 'bc':                # 1
      a_list[i:i+2] = ['S', '0']
      a_list.remove('0'); print(1)
      a_str = new_list(a_list); break
  
  k += 1
  if k > 20:
    print('there is not a solution')
    break

s = 'holai'
s = s.replace('ol','i') #s = s.replace('ol','ip'), s.rfind('ai')  index where begins and -1 when is not
s

import random

c0 = ['SS','bbc','abb']
c1 = ['bc', 'ba','aa','ca','ac','cc']
c2 = ['bc','ab']
c3 = ['ab','bc','a','c']

list1 = [c0,c1,c2,c3]

r0 = ['S', 'bc','ab']
r1 = ['S', 'bc', 'ac', 'ba', 'ab', 'bc']
r2 = ['c', 'a']
r3 = ['bc','ab','c','b']

def order(list1, res):
  for i in [len(k) for k in list1]:
    if i==3:res.append(r0)
    elif i==6:res.append(r1)
    elif i==2:res.append(r2)
    elif i==4:res.append(r3)
  return res

list1 = random.sample(list1, 4)
res = []
res = order(list1, res)
print(list1[0][0])
print(res[0][0])

s = 'acba'
s = s.replace('ba','bc')
s = s.replace('ac','ab')
s = s.replace('bbc','bc')
s

for i,j in zip(list1, res):
  for gram, word in zip(i,j):
    print(gram, word)

h = 0
while h<5:
  k = 0
  string = 'acba'
  list1 = random.sample(list1, 4)
  res = []
  res = order(list1, res)

  while k<10:
    for i,j in zip(list1, res):
      k+=1
      for gram, word in zip(i,j):
        if string.rfind(gram) != -1:
          print(string.rfind(gram), gram, word)
          string = string.replace(gram, word)    
          
    if len(string)==1:
      break
  h +=1
  print(k, string)


string == 'S'